---
- name: Retrieve the IP address
  uri:
    url: http://c31bfd6bfb009231e691-ba2be89fa62144fd02adcef310422074.r64.cf1.rackcdn.com/{{ nodepool.provider }}
    return_content: true
  register: mirror_address
  failed_when: false

- name: Ensure the registry service is running on the mirror
  command: curl --connect-timeout 3 -ks https://{{ mirror_address.content|trim }}:5000
  register: registry_check
  failed_when: false
  when: mirror_address.status == 200

- when: mirror_address.status == 200 and registry_check.rc == 0
  name: Use the mirror
  block:
  - name: Write the IP in /etc/hosts
    lineinfile:
      path: /etc/hosts
      line: "{{ mirror_address.content|trim }} my-mirror" 
    become: true
  - name: Create the podman configuration directory
    file:
      path: ~/.config/containers/
      state: directory
  - name: Copy the podman configuration
    copy:
      dest: ~/.config/containers/registries.conf
      content: |
        [[registry]]
        prefix = "quay.io/ansible/default-test-container"
        insecure = true
        blocked = false
        location = "{{ mirror_address.content|trim }}:5000/ansible/default-test-container"

        [[registry]]
        prefix = "quay.io/ansible/network-ee-unit-tests"
        insecure = true
        blocked = false
        location = "{{ mirror_address.content|trim }}:5000/ansible/network-ee-unit-tests"

        [[registry]]
        prefix = "quay.io/ansible/ansible-builder"
        insecure = true
        blocked = false
        location = "{{ mirror_address.content|trim }}:5000/ansible/ansible-builder"

        [[registry]]
        prefix = "quay.io/ansible/python-builder"
        insecure = true
        blocked = false
        location = "{{ mirror_address.content|trim }}:5000/ansible/python-builder"

        [[registry]]
        prefix = "quay.io/ansible/ansible-runner"
        insecure = true
        blocked = false
        location = "{{ mirror_address.content|trim }}:5000/ansible/ansible-runner"

  - name: Copy the Yum configuration (main)
    copy:
      dest: /etc/yum.repos.d/fedora.repo
      content: |
        [fedora]
        name=Fedora $releasever - $basearch
        failovermethod=priority
        enabled=1
        metadata_expire=7d
        repo_gpgcheck=0
        type=rpm
        gpgcheck=1
        gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
        skip_if_unavailable=False
        metalink = http://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=$basearch&protocol=http
        proxy = http://{{ mirror_address.content|trim }}:3128
        max_parallel_downloads = 10
    become: true
    when: ansible_distribution == 'Fedora'
  - name: Copy the Yum configuration (update)
    copy:
      dest: /etc/yum.repos.d/fedora-updates.repo
      content: |
        [updates]
        name=Fedora $releasever - $basearch - Updates
        failovermethod=priority
        enabled=1
        repo_gpgcheck=0
        type=rpm
        gpgcheck=1
        metadata_expire=6h
        gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
        skip_if_unavailable=False
        metalink = http://mirrors.fedoraproject.org/metalink?repo=updates-released-f$releasever&arch=$basearch&protocol=http
        proxy = http://{{ mirror_address.content|trim }}:3128
        max_parallel_downloads = 10
    become: true
    when: ansible_distribution == 'Fedora'
